server:
  port: 7072

#eureka:
#  client:
#    region: default
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: http://localhost:7074/eureka/

spring:
  application:
    name: olive-foundation-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"

# &serverTimezone=UTC
  datasource:
    url: jdbc:mysql://localhost:3306/olive?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    hibernate:
#      properties:
#        jdbc:
#          time_zone: UTC        
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect    
      
logging:
  file:
    name: ./logs/olive-foundation-server.log
carmel:
  orgId: "c79ecc86-20b7-44b2-ab70-3db893e37725"
  client_id: "olive@carmelsolutions"
  grant_type: "password"
  authBaseURL: "http://localhost:7071"
  auth-api: "http://localhost:7071/api/v1/olive-login"
  profilePicUploadPath: /Users/Anu/Desktop/temp/profile-pic
