server:
  port: 7075

spring:
  application:
    name: real-estate-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"

  datasource:
    url: jdbc:mysql://localhost:3306/realEstate?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    hibernate:  
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect    
      
logging:
  file:
    name: ./logs/real-estate-server.log
